var JSONContent = {
    C1: "",
    C2 : "",
    C3 : "",
    C4 : "",
    C5 : "",
    C6 :  "<p class='p-green'>Partout, plus prononcé en altitude. Actif pendant la chute, s’atténue rapidement.</p>",
    C7 :  "<p class='p-green'>Distribution très variable souvent prêt des crêtes. Situation plus active pendant l’épisode de transport.</p>",
    C8 :  "<p class='p-green'>Couche fragile souvent répandue en versants froids. Rupture facile aux points de moindre épaisseur.Instabilité durable.</p>",
    C9 :  "<p class='p-green'>Toutes orientation si pluie (pire en versant froid), perte de stabilité très rapide.Dépend de l’orientation et de l’altitude.</p>",
    C10 : "<p class='p-green'>Sur sols lisses ou humides. Toutes orientations mais plus fréquent en orientation ensoleillées.</p>",
    C11 : "<p class='p-red'>Départs spontanés sans lien direct avec la météo. Glissement rapide par perte de friction à l’interface neige-sol.</p>",
    C12 : "<p class='p-red'>Même par météo « neutre » un pratiquant peut rompre une C. F. persistante et provoquer un déclenchement.</p>",
    C13 : "<p class='p-red'>Déstabilisation due à l’apport d’eau (pluie ou fonte).Déclenchement d’une C.F. existante ou d’une interface ou l’eau s’est accumulée.</p>",
    C14 : "<p class='p-red'>Le transport surcharge une couche fragile.La neige récente transportée prend de la cohésion (déclenchement facile).</p>",
    C15 : "<p class='p-red'>Surcharge sur couche fragile ou formé pendant la chute.</p>",
    C16 : "<p class='p-blue'>Quantité critique de neige fraiche.Activité avalancheuse en cours.</p>",
    C17 : "<p class='p-blue'>Signes de transports de neige, d’érosion ou d’accumulation. Fissures, déclenchement de plaques dures ou friables.</p>",
    C18 : "<p class='p-blue'>Pluie sur neige fraiche : activité avalancheuse spontanée forte.Escargots au début des purgesEnfoncement en profondeur.</p>",
    C19 : "<p class='p-blue'>Se méfier des versants froids et à faibles enneigement. Whoums, fissures sous les skis, déclenchements à distance.</p>",
    C20 : "<p class='p-blue'>Souvent présence de fissures et reptations. Manteau neigeux homogène.</p>",
    C21 : "<p class='p-orange'>Quand les fissures de glissement sont apparues ? Butée en pied de pente ?</p>",
    C22 : "<p class='p-orange'>Profondeur et distribution de la couche Fragile ?Historique et observations du manteau (sondages tests) ?</p>",
    C23 : "<p class='p-orange'>Depuis quand ? Première humidification ? Profondeur humidification ? Evolution à court therme ?</p>",
    C24 : "<p class='p-orange'>Age de la neige venté ? Distribution dans la pente ?Force du vent ?</p>",
    C25 : "<p class='p-orange'>Vent en cours ? Variation de T° ? Couche de surface avant la chute ?</p>",
    C26 : "<p class='p-black'>Attention à la visibilité et pentes dominantes.Patienter 1 à 3 jours.</p>",
    C27 : "<p class='p-black'>Tracé judicieux. Evitement surtout les terrains accumulés et raides (dès prépa avec le BERA et sur le terrain).</p>",
    C28 : "<p class='p-black'>S’éloigner des versants froids si pluie forte lors de la 1ere humidification.Soleil : jouer avec orientation et horaire.</p>",
    C29 : "<p class='p-black'>Comportement défensif, au pied et à distance des pentes. Complexe, peu de signaux de surfaceInfos BERA, profils- tests.</p>",
    C30 : "<p class='p-black'>Contournement si possible. Très difficile à prévoir et à déclencher. Gestion identique aux séracs.</p>",
    C31 : "<p class='p-violet'>Avalanches de plaque sèche friable ou de neige sans cohésion. Départ spontanés ou provoqué.</p>",
    C32 : "<p class='p-violet'>Avalanches de plaque sèche friable ou dure. Départs spontanés et déclenchements provoqués possibles.</p>",
    C33 : "<p class='p-violet'>Avalanches de plaque sèche. Déclenchements provoqués.Déclenchement à distance possible Grandes propagation fréquentes.</p>",
    C34 : "<p class='p-violet'>Avalanches de plaque de neige humide ou de neige mouillé sans cohésionPrincipalement départs spontanés.</p>",
    C35 : "<p class='p-violet'>Avalanche de neige sèche ou humide toujours spontanéesDéclenchements humains et artificiels très peu probables.</p>",
    C36 : "",
    C37 : "",
    C38 : "",
    C39 : "",
    C40 : ""
};
