var JSONContent = {
    C1: "",
    C2 : "",
    C3 : "",
    C4 : "",
    C5 : "",
    C6 : "Partout, plus prononcé en altitude. Actif pendant la chute, s’atténue rapidement.",
    C7 : "Distribution très variable souvent prêt des crêtes. Situation plus active pendant l’épisode de transport.",
    C8 : "Couche fragile souvent répandue en versants froids. Rupture facile aux points de moindre épaisseur.Instabilité durable.",
    C9 : "Toutes orientation si pluie (pire en versant froid), perte de stabilité très rapide.Dépend de l’orientation et de l’altitude.",
    C10 : "Sur sols lisses ou humides. Toutes orientations mais plus fréquent en orientation ensoleillées",
    C11 : "Départs spontanés sans lien direct avec la météo. Glissement rapide par perte de friction à l’interface neige-sol.",
    C12 : "Même par météo « neutre » un pratiquant peut rompre une C. F. persistante et provoquer un déclenchement.",
    C13 : "Déstabilisation due à l’apport d’eau (pluie ou fonte).Déclenchement d’une C.F. existante ou d’une interface ou l’eau s’est accumulée.",
    C14 : "Le transport surcharge une couche fragile.La neige récente transportée prend de la cohésion (déclenchement facile)",
    C15 : "Surcharge sur couche fragile ou formé pendant la chute.",
    C16 : "Quantité critique de neige fraiche.Activité avalancheuse en cours.",
    C17 : "Signes de transports de neige, d’érosion ou d’accumulation. Fissures, déclenchement de plaques dures ou friables.",
    C18 : "Pluie sur neige fraiche : activité avalancheuse spontanée forte.Escargots au début des purgesEnfoncement en profondeur.",
    C19 : "Se méfier des versants froids et à faibles enneigement. Whoums, fissures sous les skis, déclenchements à distance.",
    C20 : "Souvent présence de fissures et reptations. Manteau neigeux homogène.",
    C21 : "Quand les fissures de glissement sont apparues ? Butée en pied de pente ?",
    C22 : "Profondeur et distribution de la couche Fragile ?Historique et observations du manteau (sondages tests) ?",
    C23 : "Depuis quand ? Première humidification ? Profondeur humidification ? Evolution à court therme ?",
    C24 : "Age de la neige venté ? Distribution dans la pente ?Force du vent ?",
    C25 : "Vent en cours ? Variation de T° ? Couche de surface avant la chute ?",
    C26 : "Attention à la visibilité et pentes dominantes.Patienter 1 à 3 jours.",
    C27 : "Tracé judicieux. Evitement surtout les terrains accumulés et raides (dès prépa avec le BERA et sur le terrain)",
    C28 : "S’éloigner des versants froids si pluie forte lors de la 1ere humidification.Soleil : jouer avec orientation et horaire",
    C29 : "Comportement défensif, au pied et à distance des pentes. Complexe, peu de signaux de surfaceInfos BERA, profils- tests",
    C30 : "Contournement si possible. Très difficile à prévoir et à déclencher. Gestion identique aux séracs",
    C31 : "Avalanches de plaque sèche friable ou de neige sans cohésion. Départ spontanés ou provoqué",
    C32 : "Avalanches de plaque sèche friable ou dure. Départs spontanés et déclenchements provoqués possibles",
    C33 : "Avalanches de plaque sèche. Déclenchements provoqués.Déclenchement à distance possible Grandes propagation fréquentes.",
    C34 : "Avalanches de plaque de neige humide ou de neige mouillé sans cohésionPrincipalement départs spontanés",
    C35 : "Avalanche de neige sèche ou humide toujours spontanéesDéclenchements humains et artificiels très peu probables.",
    C36 : "",
    C37 : "",
    C38 : "",
    C39 : "",
    C40 : ""
};
